/**
 * SpineIQ — Application Controller v2.0
 */

let currentStep = 0;
const TOTAL_STEPS = 10;
const API_PROXY_URL = 'https://spineiq-backend.onrender.com/api/generate-report';

const STEP_LABELS = [
  'Patient Info', 'Occupation', 'Work Patterns', 'Lifestyle',
  'Health Data', 'Pain Assessment', 'Radiculopathy & ODI',
  'Red Flag Screening', 'Functional Status', 'Risk Report'
];

function render() {
  const main = document.getElementById('main');
  if (!main) return;
  main.innerHTML = PAGES[currentStep]() + `
  <div class="actions">
    ${currentStep > 0 ? `<button class="btn-back" onclick="goStep(${currentStep-1})">← Previous</button>` : '<div></div>'}
    ${currentStep < TOTAL_STEPS-1 ? `<button class="btn-next" onclick="goStep(${currentStep+1})">Next step →</button>` : ''}
  </div>`;
  updateSidebar();
  updateProgress();
}

function goStep(n) { currentStep = n; function downloadReport() {
  const reportText = document.getElementById('rout')?.innerText || '';
  const sc = score();
  const sss = calcSSS();
  if (!reportText) return;

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SpineIQ Clinical Report — ${D.p.name || 'Patient'}</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
  h1 { color: #4A3F8F; font-size: 22px; border-bottom: 2px solid #4A3F8F; padding-bottom: 8px; }
  h2 { color: #4A3F8F; font-size: 16px; margin-top: 24px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; }
  .brand { font-size: 24px; font-weight: bold; color: #4A3F8F; }
  .meta { font-size: 13px; color: #666; text-align: right; }
  .scores { display: grid; grid-template-columns: repeat(5,1fr); gap: 10px; margin: 20px 0; }
  .score-box { background: #f5f3ff; border: 1px solid #c5bce8; border-radius: 8px; padding: 10px; text-align: center; }
  .score-val { font-size: 22px; font-weight: bold; color: #4A3F8F; }
  .score-lbl { font-size: 11px; color: #666; margin-top: 2px; }
  .sss-box { background: ${sss.bg.replace('var(--green-dim)','#e8f5ee').replace('var(--amber-dim)','#fdf3e3').replace('var(--red-dim)','#fceef0')}; border-radius: 10px; padding: 16px 20px; margin: 16px 0; display: flex; justify-content: space-between; align-items: center; }
  .sss-score { font-size: 40px; font-weight: bold; }
  .sss-level { font-size: 16px; font-weight: bold; padding: 8px 20px; border-radius: 20px; background: #4A3F8F; color: #fff; }
  .report-body { white-space: pre-wrap; line-height: 1.8; font-size: 14px; margin-top: 20px; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 11px; color: #999; text-align: center; }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="brand">SpineIQ</div>
    <div style="font-size:12px;color:#666">Spine Health Intelligence Platform</div>
  </div>
  <div class="meta">
    <div><strong>Patient:</strong> ${D.p.name || '—'}</div>
    <div><strong>Age:</strong> ${D.p.age || '—'} | <strong>BMI:</strong> ${D.p.bmi || '—'}</div>
    <div><strong>Date:</strong> ${new Date().toLocaleDateString('en-GB', {day:'2-digit',month:'short',year:'numeric'})}</div>
  </div>
</div>

<h2>Dimension Scores</h2>
<div class="scores">
  <div class="score-box"><div class="score-val">${sc.lifestyle}</div><div class="score-lbl">Lifestyle</div></div>
  <div class="score-box"><div class="score-val">${sc.activity}</div><div class="score-lbl">Activity</div></div>
  <div class="score-box"><div class="score-val">${sc.sleep}</div><div class="score-lbl">Sleep</div></div>
  <div class="score-box"><div class="score-val">${sc.mobility}</div><div class="score-lbl">Mobility</div></div>
  <div class="score-box"><div class="score-val">${sc.obesity}</div><div class="score-lbl">Weight</div></div>
</div>

<div class="sss-box">
  <div>
    <div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#666;margin-bottom:4px">SSS Score</div>
    <div class="sss-score">${sss.total}<span style="font-size:18px">/11</span></div>
  </div>
  <div>
    <div class="sss-level">${sss.level}</div>
    <div style="font-size:12px;color:#666;margin-top:6px;text-align:right">${sss.mgmt}</div>
  </div>
</div>

<h2>Clinical Report</h2>
<div class="report-body">${reportText}</div>

<div class="footer">
  Generated by SpineIQ — Spine Health Intelligence Platform | ${new Date().toLocaleString()}<br>
  This report is for clinical decision support only. Not a substitute for clinical judgment.
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `SpineIQ_Report_${(D.p.name||'Patient').replace(/\s+/g,'_')}_${new Date().toISOString().split('T')[0]}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

render(); }

function resetAll() {
  if (confirm('Start a new patient assessment? Current data will be cleared.')) {
    resetData(); currentStep = 0; function downloadReport() {
  const reportText = document.getElementById('rout')?.innerText || '';
  const sc = score();
  const sss = calcSSS();
  if (!reportText) return;

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SpineIQ Clinical Report — ${D.p.name || 'Patient'}</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
  h1 { color: #4A3F8F; font-size: 22px; border-bottom: 2px solid #4A3F8F; padding-bottom: 8px; }
  h2 { color: #4A3F8F; font-size: 16px; margin-top: 24px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; }
  .brand { font-size: 24px; font-weight: bold; color: #4A3F8F; }
  .meta { font-size: 13px; color: #666; text-align: right; }
  .scores { display: grid; grid-template-columns: repeat(5,1fr); gap: 10px; margin: 20px 0; }
  .score-box { background: #f5f3ff; border: 1px solid #c5bce8; border-radius: 8px; padding: 10px; text-align: center; }
  .score-val { font-size: 22px; font-weight: bold; color: #4A3F8F; }
  .score-lbl { font-size: 11px; color: #666; margin-top: 2px; }
  .sss-box { background: ${sss.bg.replace('var(--green-dim)','#e8f5ee').replace('var(--amber-dim)','#fdf3e3').replace('var(--red-dim)','#fceef0')}; border-radius: 10px; padding: 16px 20px; margin: 16px 0; display: flex; justify-content: space-between; align-items: center; }
  .sss-score { font-size: 40px; font-weight: bold; }
  .sss-level { font-size: 16px; font-weight: bold; padding: 8px 20px; border-radius: 20px; background: #4A3F8F; color: #fff; }
  .report-body { white-space: pre-wrap; line-height: 1.8; font-size: 14px; margin-top: 20px; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 11px; color: #999; text-align: center; }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="brand">SpineIQ</div>
    <div style="font-size:12px;color:#666">Spine Health Intelligence Platform</div>
  </div>
  <div class="meta">
    <div><strong>Patient:</strong> ${D.p.name || '—'}</div>
    <div><strong>Age:</strong> ${D.p.age || '—'} | <strong>BMI:</strong> ${D.p.bmi || '—'}</div>
    <div><strong>Date:</strong> ${new Date().toLocaleDateString('en-GB', {day:'2-digit',month:'short',year:'numeric'})}</div>
  </div>
</div>

<h2>Dimension Scores</h2>
<div class="scores">
  <div class="score-box"><div class="score-val">${sc.lifestyle}</div><div class="score-lbl">Lifestyle</div></div>
  <div class="score-box"><div class="score-val">${sc.activity}</div><div class="score-lbl">Activity</div></div>
  <div class="score-box"><div class="score-val">${sc.sleep}</div><div class="score-lbl">Sleep</div></div>
  <div class="score-box"><div class="score-val">${sc.mobility}</div><div class="score-lbl">Mobility</div></div>
  <div class="score-box"><div class="score-val">${sc.obesity}</div><div class="score-lbl">Weight</div></div>
</div>

<div class="sss-box">
  <div>
    <div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#666;margin-bottom:4px">SSS Score</div>
    <div class="sss-score">${sss.total}<span style="font-size:18px">/11</span></div>
  </div>
  <div>
    <div class="sss-level">${sss.level}</div>
    <div style="font-size:12px;color:#666;margin-top:6px;text-align:right">${sss.mgmt}</div>
  </div>
</div>

<h2>Clinical Report</h2>
<div class="report-body">${reportText}</div>

<div class="footer">
  Generated by SpineIQ — Spine Health Intelligence Platform | ${new Date().toLocaleString()}<br>
  This report is for clinical decision support only. Not a substitute for clinical judgment.
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `SpineIQ_Report_${(D.p.name||'Patient').replace(/\s+/g,'_')}_${new Date().toISOString().split('T')[0]}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

render();
  }
}

function updateSidebar() {
  document.querySelectorAll('.sitem[data-s]').forEach((el, i) => {
    el.classList.toggle('active', i === currentStep);
    el.classList.toggle('done',   i <  currentStep);
    const num = el.querySelector('.step-num');
    if (num) num.textContent = i < currentStep ? '✓' : i + 1;
  });
}

function updateProgress() {
  const pct = Math.round(((currentStep + 1) / TOTAL_STEPS) * 100);
  const pctEl  = document.getElementById('sp-pct');
  const fillEl = document.getElementById('sp-fill');
  if (pctEl)  pctEl.textContent  = pct + '%';
  if (fillEl) fillEl.style.width = pct + '%';
}

function updBMI() {
  const h = document.getElementById('ht')?.value || D.p.height;
  const w = document.getElementById('wt')?.value || D.p.weight;
  D.p.height = h; D.p.weight = w; D.p.bmi = calcBMI(h, w);
  const el = document.getElementById('bmi-bd');
  if (el) {
    el.textContent = D.p.bmi ? `${D.p.bmi} — ${bmiLbl(D.p.bmi)}` : 'Enter height & weight';
    el.style.color = bmiCol(D.p.bmi);
  }
}

function checkSitting() {
  const el = document.getElementById('sitting-alert');
  if (!el) return;
  el.innerHTML = D.wp.sitting > 8
    ? `<div class="alert alert-warn">⚠ ${D.wp.sitting}h sitting/day exceeds safe limits. Primary driver of disc degeneration and back pain.</div>` : '';
}

async function genReport() {
  const btn = document.getElementById('gbtn');
  const out = document.getElementById('rout');
  if (!btn || !out) return;
  btn.disabled = true; btn.textContent = 'Generating…';
  out.innerHTML = `<div class="gen-loading"><div class="spinner"></div>Waking up server — may take up to 30 seconds on first use…</div>`;
  try { await fetch(API_PROXY_URL.replace('/api/generate-report', ''), { method: 'GET' }); } catch(e) {}
  out.innerHTML = `<div class="gen-loading"><div class="spinner"></div>Analysing patient data and generating evidence-based clinical report…</div>`;
  const sc = score();
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 90000);
    const response = await fetch(API_PROXY_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: buildReportPrompt(sc) }),
      signal: controller.signal
    });
    clearTimeout(timeout);
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || 'Server error');
    out.innerHTML = `<div class="report-box">${data.report}</div>`;
    // Show download button
    const wrap = document.getElementById('download-wrap');
    if (wrap) wrap.innerHTML = `
      <button onclick="downloadReport()" style="width:100%;margin-top:12px;padding:12px;border-radius:var(--r2);
        background:var(--bg3);border:1px solid var(--border2);color:var(--text2);font-size:14px;font-weight:500;
        cursor:pointer;font-family:Inter,sans-serif;display:flex;align-items:center;justify-content:center;gap:8px;
        transition:all .15s" onmouseover="this.style.background='var(--bg4)'" onmouseout="this.style.background='var(--bg3)'">
        ⬇ Download Report as PDF
      </button>`;
  } catch (err) {
    console.error('SpineIQ report error:', err);
    out.innerHTML = `<div class="report-box" style="color:var(--red)">Report generation failed. Please click Regenerate — the server may still be waking up.</div>`;
  }
  btn.disabled = false; btn.textContent = '✦ Regenerate Report';
}

function downloadReport() {
  const reportText = document.getElementById('rout')?.innerText || '';
  const sc = score();
  const sss = calcSSS();
  if (!reportText) return;

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SpineIQ Clinical Report — ${D.p.name || 'Patient'}</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
  h1 { color: #4A3F8F; font-size: 22px; border-bottom: 2px solid #4A3F8F; padding-bottom: 8px; }
  h2 { color: #4A3F8F; font-size: 16px; margin-top: 24px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; }
  .brand { font-size: 24px; font-weight: bold; color: #4A3F8F; }
  .meta { font-size: 13px; color: #666; text-align: right; }
  .scores { display: grid; grid-template-columns: repeat(5,1fr); gap: 10px; margin: 20px 0; }
  .score-box { background: #f5f3ff; border: 1px solid #c5bce8; border-radius: 8px; padding: 10px; text-align: center; }
  .score-val { font-size: 22px; font-weight: bold; color: #4A3F8F; }
  .score-lbl { font-size: 11px; color: #666; margin-top: 2px; }
  .sss-box { background: ${sss.bg.replace('var(--green-dim)','#e8f5ee').replace('var(--amber-dim)','#fdf3e3').replace('var(--red-dim)','#fceef0')}; border-radius: 10px; padding: 16px 20px; margin: 16px 0; display: flex; justify-content: space-between; align-items: center; }
  .sss-score { font-size: 40px; font-weight: bold; }
  .sss-level { font-size: 16px; font-weight: bold; padding: 8px 20px; border-radius: 20px; background: #4A3F8F; color: #fff; }
  .report-body { white-space: pre-wrap; line-height: 1.8; font-size: 14px; margin-top: 20px; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 11px; color: #999; text-align: center; }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="brand">SpineIQ</div>
    <div style="font-size:12px;color:#666">Spine Health Intelligence Platform</div>
  </div>
  <div class="meta">
    <div><strong>Patient:</strong> ${D.p.name || '—'}</div>
    <div><strong>Age:</strong> ${D.p.age || '—'} | <strong>BMI:</strong> ${D.p.bmi || '—'}</div>
    <div><strong>Date:</strong> ${new Date().toLocaleDateString('en-GB', {day:'2-digit',month:'short',year:'numeric'})}</div>
  </div>
</div>

<h2>Dimension Scores</h2>
<div class="scores">
  <div class="score-box"><div class="score-val">${sc.lifestyle}</div><div class="score-lbl">Lifestyle</div></div>
  <div class="score-box"><div class="score-val">${sc.activity}</div><div class="score-lbl">Activity</div></div>
  <div class="score-box"><div class="score-val">${sc.sleep}</div><div class="score-lbl">Sleep</div></div>
  <div class="score-box"><div class="score-val">${sc.mobility}</div><div class="score-lbl">Mobility</div></div>
  <div class="score-box"><div class="score-val">${sc.obesity}</div><div class="score-lbl">Weight</div></div>
</div>

<div class="sss-box">
  <div>
    <div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#666;margin-bottom:4px">SSS Score</div>
    <div class="sss-score">${sss.total}<span style="font-size:18px">/11</span></div>
  </div>
  <div>
    <div class="sss-level">${sss.level}</div>
    <div style="font-size:12px;color:#666;margin-top:6px;text-align:right">${sss.mgmt}</div>
  </div>
</div>

<h2>Clinical Report</h2>
<div class="report-body">${reportText}</div>

<div class="footer">
  Generated by SpineIQ — Spine Health Intelligence Platform | ${new Date().toLocaleString()}<br>
  This report is for clinical decision support only. Not a substitute for clinical judgment.
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `SpineIQ_Report_${(D.p.name||'Patient').replace(/\s+/g,'_')}_${new Date().toISOString().split('T')[0]}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

render();
